def raises_value_error():
  raise ValueError
  
try:
  raises_value_error()
except ValueError:
  print("You raised a ValueError!")
  
def divide_two_numbers(x, y):
  result = x / y
  return result

def in_range(num, lower, upper):
  if num >= lower and num <= upper:
    return True
  else:
    return False

try:
  result = divide_two_numbers(2,0)
  print(result)
except NameError:
  print("A NameError occurred.")
except ValueError:
  print("A ValueError occurred.") 
except ZeroDivisionError:
  print("A ZeroDivisionError occurred.")
  
  
